apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: any-user-binding-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "any-user-{{ .Chart.Name }}"
