apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: any-user-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - services: 
    - "{{ .Chart.Name }}.{{ .Values.namespace }}.svc.cluster.local"
    paths: ["*"]
    methods: ["*"]
