apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /api/{{ .Values.namespace }}/{{ .Values.subdomainName }}/
      rewrite:
        uri: /api/
      route:
        - destination:
             host: "{{ .Chart.Name }}.{{ .Values.namespace }}.svc.cluster.local"
             port:
               number: {{ .Values.service.servicePort }}
